name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to deploy"
        required: true
        type: string

jobs:
  create-release:
    name: "Create Release"
    runs-on: windows-latest
    environment: "release"
    steps:
      - run: echo "Version being built is ${{ github.event.inputs.version }}"

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # 2.9.1
        with:
          cache-all-crates: true
          cache-on-failure: true
          cache-bin: true

      - name: Run winget-releaser
        uses: ClementTsang/winget-releaser@8fd76865f5ebae36f78a4884c642b9edf646ad26
        with:
          identifier: Clement.bottom
          installers-regex: '^bottom_.+_installer\.msi$' # Should catch both x86 and ARM
          version: ${{ github.event.inputs.version }}
          release-tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
          release-repository: "bottom"
