name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to deploy"
        required: true
        type: string

jobs:
  create-release:
    name: "Create Release"
    runs-on: windows-latest
    environment: "release"
    steps:
      - run: echo "Version being built is ${{ github.event.inputs.version }}"

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # 2.9.2
        with:
          cache-all-crates: true
          cache-on-failure: true
          cache-bin: true

      - name: Run winget-releaser
        uses: ClementTsang/winget-releaser@1dfef8fada4f62c89ecb755ea7ed4e80c1857bfb
        with:
          identifier: Clement.bottom
          installers-regex: '^bottom_.+_installer\.msi$' # Should catch both x86 and ARM
          version: ${{ github.event.inputs.version }}
          release-tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
          release-repository: "bottom"
